### PR TITLE
CA, unit tests, added view model for time estimation

### PR DESCRIPTION
**Pull request by utcjcao**

### CODE REVIEW

**Comment by utcjcao** [comment]
added daos

**Review by venniseho — APPROVED** [review]
CA generally looks good! DAO should work with all our interfaces too so that's perfect. Looks good to me.

**Review by RF216 — COMMENTED** [review]
Looks good, may or may not conflict with Royce's branch, so check for that during merging, but other than that should be good.

**Review by 3laine3 — COMMENTED** [review]
Overall, the clean architecture and unit tests look good and comprehensive. 

One thing to consider is that it might be better to change the chatbotViewModel names to a more specific name like chatbotTimeEstimateViewModel if we want to have two chatbot views (will work better in appbuilder and more clear for CA). Also, on that note, remember to change the actual text values in view model to display to correct instructions for time estimating.

Also, the newly created ChatbotInputData and ChatbotOutputData can be deleted and both chatbot views can share the same original ones because they both just input a user input and output the cohere response.

**Review by RoyceLuo1216 — APPROVED** [review]
Looks good, CA is done, just make sure to connect it to the view for chatbot, and make sure that it works in tandem with event conflicts

**Pull request merged**
